# Generated by Django 3.2.4 on 2021-06-27 05:15

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='common/')),
                ('nickname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('W', '여성'), ('M', '남성')], default='W', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=50)),
                ('studentID', models.IntegerField(default=0)),
                ('sleep_habit', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10)),
                ('sleep_time', models.CharField(choices=[('D', 'D'), ('E', 'E'), ('F', 'F')], default='D', max_length=10)),
                ('cleanliness', models.CharField(choices=[('G', 'G'), ('H', 'H'), ('I', 'I')], default='G', max_length=10)),
                ('cook', models.CharField(choices=[('J', 'J'), ('K', 'K'), ('L', 'L')], default='J', max_length=10)),
                ('smoke', models.BooleanField(default=False)),
                ('budget', models.CharField(choices=[('M', 'M'), ('N', 'N'), ('O', 'O')], default='M', max_length=10)),
                ('hope_area', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('profile_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
