# Generated by Django 3.2.4 on 2021-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='budget',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cleanliness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cook',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='introduction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sleep_habit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sleep_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='smoke',
            field=models.CharField(choices=[('N', '비흡연자'), ('Y', '흡연자')], default='비흡연자', max_length=10),
        ),
    ]
